services:
  db:
    image: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=domjudge
      - MARIADB_USER=domjudge
      - MARIADB_PASSWORD=domjudge
      - MARIADB_DATABASE=domjudge
    ports:
      - 3306:3306
      - 2631:631
    command: --max-connections=1000 --max-allowed-packet=512M
    volumes:
      - sqldata:/var/lib/mysql
  domjudge:
    image: rmartinsanta/domserver:latest
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    ports:
      - 80:80
    environment:
      - MYSQL_HOST=db
      - MYSQL_ROOT_PASSWORD=domjudge
      - MYSQL_USER=domjudge
      - MYSQL_PASSWORD=domjudge
      - MYSQL_DATABASE=domjudge
      - JUDGEDAEMON_USERNAME=judgehost
      - JUDGEDAEMON_PASSWORD=password
  jh:
    image: rmartinsanta/judgehost:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys/fs/cgroup:/sys/fs/cgroup
    environment:
#      - DAEMON_ID=0  # Daemon ID will be configured at runtime
      - DOMSERVER_HOST=domjudge
      - DOMSERVER_BASEURL=http://domjudge/
      - JUDGEDAEMON_USERNAME=judgehost
      - JUDGEDAEMON_PASSWORD=domjudge
    privileged: true

volumes:
  sqldata:
